spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    dynamic:
      primary: primary
      strict: false
      datasource:
        primary:
          url: jdbc:mysql://localhost:3306/test?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
          username: root
          password: root123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat,wall,log4j2
          maxActive: 10
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 100000
          # 最大 900000
          maxEvictableIdleTimeMillis: 900000
          # 最小 600000
          minEvictableIdleTimeMillis: 600000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          keepAlive: true
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          #
          minPoolSize: 3
          maxPoolSize: 25
          maxLifetime: 20000
          borrowConnectionTimeout: 30
          loginTimeout: 30
          maintenanceInterval: 60
          maxIdleTime: 60
        secondary:
          url: jdbc:mysql://localhost:3306/test2?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
          username: root
          password: root123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat,wall,log4j2
          maxActive: 10
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 100000
          # 最大 900000
          maxEvictableIdleTimeMillis: 900000
          # 最小 600000
          minEvictableIdleTimeMillis: 600000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          keepAlive: true
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          #
          minPoolSize: 3
          maxPoolSize: 25
          maxLifetime: 20000
          borrowConnectionTimeout: 30
          loginTimeout: 30
          maintenanceInterval: 60
          maxIdleTime: 60
        tertiary:
          url: jdbc:mysql://localhost:3306/test3?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
          username: root
          password: root123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat,wall,log4j2
          maxActive: 10
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 100000
          # 最大 900000
          maxEvictableIdleTimeMillis: 900000
          # 最小 600000
          minEvictableIdleTimeMillis: 600000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          keepAlive: true
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          #
          minPoolSize: 3
          maxPoolSize: 25
          maxLifetime: 20000
          borrowConnectionTimeout: 30
          loginTimeout: 30
          maintenanceInterval: 60
          maxIdleTime: 60

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/**/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名
  typeAliasesPackage:
  # 枚举类 扫描路径
  typeEnumsPackage: com.coral.**.enums
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #数据库类型
      #db-type: MYSQL
      # 表名前缀
      table-prefix:
    banner: false
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

